export const API_URL = process.env.EXPO_PUBLIC_API_URL!;
export const BETTER_AUTH_BASE_URL = process.env.EXPO_PUBLIC_BETTER_AUTH_BASE_URL!;
export const EAS_PROJECT_ID = process.env.EXPO_PUBLIC_EAS_PROJECT_ID!;
export const REVENUE_CAT_APPLE_API_KEY = process.env.EXPO_PUBLIC_REVENUE_CAT_APPLE_API_KEY!;
export const GOOGLE_IOS_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID!;
export const GOOGLE_WEB_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID!;